version: '2.4'

services:
  node-app:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - 3333:3000
    command: yarn start:dev

volumes:
  node_modules:
