version: '2.4'

services:
  node-app:
    build:
      dockerfile: ./docker/node.development.Dockerfile
      context: ../
    environment:
      - MONGO_URL=mongodb://rootuser:supersecurepassword@mongo:27017/usersdb
    volumes:
      - ../:/usr/src/app/
      - ../node_modules:/usr/src/app/node_modules
      # - ../dist:/usr/src/app/dist # debug
    ports:
      # - 9119:9229 #debug
      - ${PORT:-3000}:3333

  mongo:
    image: mongo:4.2.2
    container_name: 'mongodb'
    environment:
      - MONGO_INITDB_DATABASE=usersdb
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=supersecurepassword
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - 27017:27017
