# https://medium.com/faun/managing-mongodb-on-docker-with-docker-compose-26bf8a0bbae3

version: '2.4'

services:
  node-app:
    build:
      dockerfile: ./docker/node.development.Dockerfile
      context: ../
    volumes:
      - ../:/usr/src/app/
      - ../node_modules:/usr/src/app/node_modules
    ports:
      - ${PORT:-3333}:3333

  mongo:
    image: mongo:4.2.2
    container_name: 'mongodb'
    environment:
      - MONGO_INITDB_DATABASE=usersdb
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=supersecurepassword
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - 27017:27017
